### ISSUE TITLE
aligning fullwidth character

### ISSUE THREAD

**Issue by yoyoys** [mechatroner/vscode_rainbow_csv#81] opened 2020-12-28 03:10 UTC
Hi

Currently fullwidth character like `許功蓋`(East Asian character) or `😃`(emiji) didn't detect with double with(like double byte).

Is there any plan to support fullwith character? Thanks!

reference:
[Halfwidth_and_fullwidth_forms](https://en.wikipedia.org/wiki/Halfwidth_and_fullwidth_forms)

**Comment by mechatroner** [comment] 2020-12-30 04:34
Hi @yoyoys,
Yes, I really want to fix the alignment for Asian characters. The problem is that I am not quite sure how to do this properly, and I don't currently have time to work on this, so PRs are welcome!

I am closing the ticket in favor of #69

**Closed by mechatroner** 2020-12-30 04:34 UTC
