### ISSUE TITLE
"Dynamic CSV" highlighting conflicts with other extensions and colors are not consistent with textmate grammars. 

### ISSUE THREAD

**Issue by sentience** [mechatroner/vscode_rainbow_csv#149] opened 2023-10-18 04:19 UTC
Sample CSV file (filename: entries.csv):

```csv
id,title,url,quadrant,moved,ringId,date
nodejs,NodeJS,x,frontend,0,adopt,20/4/21
nodejs,NodeJS,x,frontend,0,adopt,20/4/21
nodejs,NodeJS,x,frontend,0,adopt,20/4/21
nodejs,NodeJS,x,frontend,0,adopt,20/4/21
nodejs,NodeJS,x,frontend,0,adopt,20/4/21
nodejs,NodeJS,x,frontend,0,adopt,20/4/21
nodejs,NodeJS,x,frontend,0,adopt,20/4/21
nodejs,NodeJS,x,frontend,0,adopt,20/4/21
nodejs,NodeJS,x,frontend,0,adopt,20/4/21
nodejs,NodeJS,x,frontend,0,adopt,20/4/21
nodejs,NodeJS,x,frontend,0,adopt,20/4/21
nodejs,NodeJS,x,frontend,0,adopt,20/4/21
```

This file is correctly highlighted with rainbow columns when opened with file type "CSV (csv)":

![CleanShot 2023-10-18 at 15 17 58](https://github.com/mechatroner/vscode_rainbow_csv/assets/89772/86333dda-bb74-49bc-94c4-ea93c5d6db58)

But when I switch to Dynamic CSV (which I want to use because it supports multi-line quoted strings), and I specify "," as the separator character, the file is not highlighted at all:

![CleanShot 2023-10-18 at 15 19 20](https://github.com/mechatroner/vscode_rainbow_csv/assets/89772/0569404a-10ea-48dd-9a75-62e78b6074dd)

**Comment by mechatroner** [comment] 2023-10-19 02:42
I just tried this with the same filename and content and could not reproduce it.

Silly question: do you press "enter" after entering `,` in the "Dynamic CSV" dialog?
Also: what does the file type show in the bottom right corner show? And what happens if you switch back and forth between the current and some other files?

Could you also please do the following test for me - copy the file (e.g. as entries_rfc.csv) and modify its context as follows:
```
id,title,url,quadrant,moved,ringId,date
nodejs,NodeJS,x,frontend,0,"adopt ->
-> next line continuation",20/4/21
nodejs,NodeJS,x,frontend,0,adopt,20/4/21
nodejs,NodeJS,x,frontend,0,adopt,20/4/21
nodejs,NodeJS,x,frontend,0,adopt,20/4/21
nodejs,NodeJS,x,frontend,0,adopt,20/4/21
nodejs,NodeJS,x,frontend,0,adopt,20/4/21
nodejs,NodeJS,x,frontend,0,adopt,20/4/21
nodejs,NodeJS,x,frontend,0,adopt,20/4/21
nodejs,NodeJS,x,frontend,0,adopt,20/4/21
nodejs,NodeJS,x,frontend,0,adopt,20/4/21
nodejs,NodeJS,x,frontend,0,adopt,20/4/21
nodejs,NodeJS,x,frontend,0,adopt,20/4/21
```
and then open the new file in VSCode - does it autodetect it as "Dynamic CSV" and apply the highlighting?

Could you also please check if you are running the latest version of VSCode and Rainbow CSV?

**Comment by mechatroner** [comment] 2023-10-21 02:19
Actually, I have an idea what the problem could be - it looks like the extension allows to set the separator only once, so if it was mistyped the very first time - there is no way to re-enter it again. The choice is somehow kept even between VSCode restarts.

**Comment by sentience** [comment] 2023-10-23 01:41
> Silly question: do you press "enter" after entering `,` in the "Dynamic CSV" dialog?

Yep, certainly do.

> Also: what does the file type show in the bottom right corner show?

It shows "Dynamic CSV".

> And what happens if you switch back and forth between the current and some other files?

No change. The CSV remains un-highlighted.

> Could you also please do the following test for me - copy the file (e.g. as entries_rfc.csv) and modify its context as follows:
> …
> 
> and then open the new file in VSCode - does it autodetect it as "Dynamic CSV" and apply the highlighting?

When I first save the file, VSCode selects file type CSV and the content is highlighted (but the highlighting of the multi-line string is broken, of course.

When I close and reopen the file, VSCode opens it as Dynamic CSV with no highlighting.

> Could you also please check if you are running the latest version of VSCode and Rainbow CSV?

I'm using the current VSCode 1.84.0-insider build, and Rainbow CSV 3.7.1.

**Comment by sentience** [comment] 2023-10-23 01:44
> Actually, I have an idea what the problem could be - it looks like the extension allows to set the separator only once, so if it was mistyped the very first time - there is no way to re-enter it again. The choice is somehow kept even between VSCode restarts.

Hmm, does that prevent the separator from being updated with the command **Rainbow CSV: Set separator - Quoted Multiline Fields**? When I select a comma and run that command, nothing changes.

I should also mention that the tooltips for the columns correctly show the column titles, so it does appear that the columns are being correctly parsed.

![CleanShot 2023-10-23 at 12 44 28](https://github.com/mechatroner/vscode_rainbow_csv/assets/89772/60706caf-f932-4f37-80c2-76a0c9cc7b3a)

**Comment by sentience** [comment] 2023-10-23 02:00
My issue appears to be a conflict with some other extension. Running VS Code with only Rainbow CSV enabled, the highlighting of the Dynamic CSV file type works.

**Comment by sentience** [comment] 2023-10-23 02:13
OK, so the issue appears to be that many third-party color themes _do not_ provide colors for the highlighting produced by Dynamic CSV, but _do_ provide colors for the highlighting produced by CSV.

Are these two modes doing something significantly different in how they apply colors to the document?

**Comment by mechatroner** [comment] 2023-10-23 21:42
> My issue appears to be a conflict with some other extension.


Oh, wow, it is great to know that an extension conflict could cause this, I wasn't even considering such a possibility. Can you share what is the other extension that is causing this? I might look into the conflict mechanism when I have some spare time.

> Are these two modes doing something significantly different in how they apply colors to the document?

Yes, CSV is powered by pre-created textmate language grammar, while "Dynamic CSV" parses the current fragment of the file on the fly and applies the highlighting via VSCode "Semantic tokenization" mechanism. There was some issue regarding how different token types are highlighted in Semantic tokenization vs pre-created grammars, but I forgot the details. Most likely the best I can do currently is to add an instruction on how to customize highlighting for "Dynamic CSV" case.

**Comment by mechatroner** [comment] 2023-10-24 01:48
I just checked the docs again and it looks like there is a way to properly set up semantic token fallback mapping: https://code.visualstudio.com/api/language-extensions/semantic-highlight-guide#custom-textmate-scope-mappings Not sure if I've seen/tried this before, so I will take a look at some point.

**Comment by mechatroner** [comment] 2024-01-03 02:14
I fixed inconsistent "dynamic csv" colors in version 3.10.0
I also found and fixed a bug that was preventing "dynamic csv" coloring from working with many custom color themes which might have caused the original problem.

**Closed by mechatroner** 2024-01-03 02:14 UTC
