### ISSUE TITLE
Line break in quoted field parsed incorrect

### ISSUE THREAD

**Issue by Lemm1** [mechatroner/vscode_rainbow_csv#47] opened 2019-11-25 12:05 UTC
Due to [RFC 4180](https://tools.ietf.org/html/rfc4180#page-2) CSV field can contain line break symbol and if it quoted it must be treated as same field not new line. Following example csv data from RFS standard treated as 3 different rows in Rainbow CSV not 2 rows as it should:

"aaa","b  
bb","ccc"
zzz,yyy,xxx

**Comment by mechatroner** [comment] 2019-11-25 12:09
Duplicate of #4

**Closed by mechatroner** 2019-11-25 12:09 UTC
